export const DEFAULT_CONFIG = {
  ia: {
    usar_ia: false,
    sugerir_respostas: true,
    corrigir_texto: false,
    auto_completar: false,
    resumo_conversa: true,
    classificar_intencao: true,
    sugerir_tags: true,
  },
  automacoes: {
    encerrar_automatico_min: 0,
    mensagem_encerramento_inatividade: "-conversa encerrada por conta de inatividade-",
    transferir_para_humano_apos_bot: true,
    limite_mensagens_bot: 5,
    auto_assumir: false,
    reabrir_automaticamente: false,
  },
  chatbot_triage: {
    enabled: false,
    welcomeMessage: "",
    invalidOptionMessage: "Opção inválida. Por favor, responda apenas com o número do setor desejado.",
    confirmSelectionMessage: "Perfeito! Seu atendimento foi direcionado para o setor {{departamento}}. Em instantes nossa equipe dará continuidade.",
    enviarMensagemFinalizacao: false,
    mensagemFinalizacao: "Atendimento finalizado com sucesso. (Segue seu protocolo: {{protocolo}}.\nPor favor, informe uma nota entre 0 e 10 para avaliar o atendimento prestado.)",
    foraHorarioEnabled: false,
    horarioInicio: "09:00",
    horarioFim: "18:00",
    diasSemanaDesativados: [0, 6],
    datasEspecificasFechadas: [],
    mensagemForaHorario: "Olá! Nosso horário de atendimento é de segunda a sexta, das 09h às 18h. Sua mensagem foi recebida e retornaremos no próximo dia útil. Obrigado!",
    intervaloEnvioSegundos: 3,
    sendOnlyFirstTime: true,
    fallbackToAI: false,
    businessHoursOnly: false,
    transferMode: "departamento",
    tipo_distribuicao: "fila",
    reopenMenuCommand: "0",
    options: [],
    finalizar_por_ausencia_ativo: false,
    finalizar_por_ausencia_prazo: 24,
    finalizar_por_ausencia_unidade: "horas_corridas",
    finalizar_por_ausencia_enviar_mensagem: false,
    finalizar_por_ausencia_mensagem: "",
    finalizar_por_ausencia_reabrir_automaticamente: true,
    finalizar_por_ausencia_reabrir_sem_chatbot: true,
    redirecionar_sem_resposta_ativo: false,
    redirecionar_sem_resposta_minutos: 5,
    redirecionar_sem_resposta_departamento_id: null,
  },
  admin_atendimento_alerta: {
    ativo: false,
    cliente_id: null,
    cliente_nome: "",
    telefone_admin: "",
    horario_envio: "09:00",
    timezone: "",
    incluir_nota_media: false,
    incluir_conversas_sem_resposta: true,
  },
};

export const DEFAULT_ALERTA_SEM_RESPOSTA = {
  alerta_sem_resposta_ativo: false,
  tempo_primeiro_alerta_minutos: 1,
  tempo_alerta_critico_minutos: 3,
  tempo_notificar_gestor_minutos: 5,
  notificar_por_whatsapp: false,
  notificar_por_email: false,
  notificar_interno: true,
  reabrir_conversa_automaticamente: true,
  aplicar_tag_automatica: true,
  nome_tag_automatica: "Reaberta por falta de resposta",
  gestor_notificado_id: null,
  gestor_cliente_id: null,
  gestor_cliente_nome: "",
  responsaveis_notificacao_ids: [],
  telefone_gestor: "",
  horario_comercial_ativo: true,
  timezone: "America/Sao_Paulo",
  horarioInicio: "09:00",
  horarioFim: "18:00",
  diasSemanaDesativados: [0, 6],
  datasEspecificasFechadas: [],
  horario_comercial: null,
};
